### ISSUE TITLE
src/common.hpp:13:10: fatal error: curl/curl.h: No such file

### ISSUE THREAD

**Issue by thoje620** [bo1929/krepp#1]
Hi 
I followed the installation
```
git clone --recurse-submodules -j8 https://github.com/bo1929/krepp.git
cd krepp 
```

and faced this
```
$ make
g++ -Wno-unused-result -Wno-unused-command-line-argument -std=c++17 -O3 -g -fopenmp -I/data/apps/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include  -lstdc++fs -lm -lz -lstdc++ -lcurl -Iexternal/CLI11/include/CLI -Iexternal/parallel-hashmap -Iexternal/boost/libs/math/include -c src/common.cpp -o build/common.o
In file included from src/common.cpp:1:
src/common.hpp:13:10: fatal error: curl/curl.h: No such file or directory
   13 | #include <curl/curl.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [makefile:27: build/common.o] Error 1
```
Any help?

**Comment by bo1929** [comment]
Hi,

You seem to lack `libcurl` on your system, which is a requirement for downloading reference genomes directly from FTP servers. I will make it optional soon, for now, you can just install it by running (Ubuntu/Debian)
```
sudo apt install curl
```
For other operating systems, you can check [this](https://ec.haxx.se/install/linux.html).

Let me know if this works!

**Comment by thoje620** [comment]
thanks for fast response. I don't have sudo access. I tried with conda there was some other version issues. I'll research to find an alternative way.

**Comment by bo1929** [comment]
Sure! I'll try to make a release that doesn't require `libcurl` today.

**Comment by bo1929** [comment]
Hi,

I added a branch as a temporary workaround for removing the `libcurl` dependency. The below commands should be able to compile `krepp`:
```bash
git clone -b libcurl-free --recurse-submodules -j8 https://github.com/bo1929/krepp.git
cd krepp && make
```

There is also a [release](https://github.com/bo1929/krepp/releases/tag/v0.0.2-no_libcurl) for this version.

Let me know if this works!

**Comment by thoje620** [comment]
Awesome! thanks
I just faced an error with 
```
g++ -Wno-unused-result -Wno-unused-command-line-argument -std=c++17 -O3 -g -fopenmp build/common.o build/MurmurHash3.o build/lshf.o build/index.o build/query.o build/rqseq.o build/record.o build/phytree.o build/table.o build/krepp.o -lstdc++fs -lm -lz -lstdc++ -lcurl -I/data/apps//lib/gcc/x86_64-pc-linux-gnu/9.3.0/include  -Iexternal/CLI11/include/CLI -Iexternal/parallel-hashmap -Iexternal/boost/libs/math/include -o krepp
/usr/bin/ld: cannot find -lcurl
collect2: error: ld returned 1 exit status
make: *** [makefile:30: krepp] Error 1
```

then I removed `-lcurl` from makefile and make it again, it was smooth and finished successfully. I was able to build index for a set of genomes and a tree, and  find distances for some reads. Thanks for developing this interesting tool.  
All the best.

**Comment by bo1929** [comment]
Excellent, I'm glad it worked!

I've removed `-lcurl` flag from the makefile on `libcurl-free` branch, thanks for letting me know.
